import { describe, it, expect } from 'vitest';
import { parseLockfile } from '../../src/utils/lockfile.ts';

describe('lockfile parser', () => {
  describe('package-lock.json', () => {
    it('parses basic package-lock.json v2', () => {
      const content = JSON.stringify({
        name: 'test',
        version: '1.0.0',
        lockfileVersion: 2,
        packages: {
          '': { name: 'test', version: '1.0.0' },
          'node_modules/lodash': { version: '4.17.21', resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz', integrity: 'sha512-...' },
          'node_modules/react': { version: '18.2.0', dev: true },
        },
      });

      const result = parseLockfile('package-lock.json', content);
      expect(result.has('lodash')).toBe(true);
      expect(result.get('lodash')?.version).toBe('4.17.21');
      expect(result.get('lodash')?.dev).toBe(false);
      expect(result.get('lodash')?.integrity).toBe('sha512-...');
      expect(result.has('react')).toBe(true);
      expect(result.get('react')?.dev).toBe(true);
    });

    it('resolves nested node_modules entries to the deepest package name', () => {
      const content = JSON.stringify({
        lockfileVersion: 3,
        packages: {
          '': { name: 'root', version: '1.0.0' },
          'node_modules/a': { version: '1.0.0' },
          'node_modules/a/node_modules/b': { version: '2.0.0', dev: true },
          'node_modules/@scope/pkg': { version: '3.0.0' },
        },
      });

      const result = parseLockfile('package-lock.json', content);
      expect(result.has('b')).toBe(true);
      expect(result.get('b')?.version).toBe('2.0.0');
      expect(result.get('b')?.dev).toBe(true);
      expect(result.has('@scope/pkg')).toBe(true);
      expect(result.has('a/node_modules/b')).toBe(false);
    });

    it('parses legacy lockfileVersion 1 dependencies including nested ones', () => {
      const content = JSON.stringify({
        lockfileVersion: 1,
        dependencies: {
          lodash: { version: '4.17.21', resolved: 'https://r/lodash.tgz' },
          express: {
            version: '4.18.2',
            dev: true,
            dependencies: { 'body-parser': { version: '1.20.1' } },
          },
        },
      });

      const result = parseLockfile('npm-shrinkwrap.json', content);
      expect(result.get('lodash')?.version).toBe('4.17.21');
      expect(result.get('express')?.dev).toBe(true);
      expect(result.get('body-parser')?.version).toBe('1.20.1');
    });

    it('returns an empty map for invalid JSON', () => {
      expect(parseLockfile('package-lock.json', '{not json').size).toBe(0);
    });
  });

  describe('yarn.lock', () => {
    it('parses basic yarn.lock', () => {
      const content = `# yarn lockfile v1
"lodash@^4.17.21":
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-lodash==
`;

      const result = parseLockfile('yarn.lock', content);
      expect(result.has('lodash')).toBe(true);
      expect(result.get('lodash')?.version).toBe('4.17.21');
      expect(result.get('lodash')?.integrity).toBe('sha512-lodash==');
    });

    it('parses scoped packages and comma separated patterns', () => {
      const content = `# yarn lockfile v1
"@scope/pkg@^2.0.0", "@scope/pkg@~2.1.0":
  version "2.1.3"
  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-2.1.3.tgz"

left-pad@^1.3.0:
  version "1.3.0"
`;

      const result = parseLockfile('yarn.lock', content);
      expect(result.get('@scope/pkg')?.version).toBe('2.1.3');
      expect(result.get('left-pad')?.version).toBe('1.3.0');
    });

    it('parses yarn berry entries', () => {
      const content = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0/abc
  languageName: node
  linkType: hard
`;

      const result = parseLockfile('yarn.lock', content);
      expect(result.get('lodash')?.version).toBe('4.17.21');
      expect(result.get('lodash')?.resolved).toBe('lodash@npm:4.17.21');
      expect(result.has('__metadata')).toBe(false);
    });
  });

  describe('pnpm-lock.yaml', () => {
    it('parses pnpm lockfileVersion 5 style dependency sections', () => {
      const content = `
dependencies:
  lodash: 4.17.21
devDependencies:
  typescript: 5.0.0
specifiers:
  lodash: ^4.17.21
  typescript: ^5.0.0

packages:
  /lodash/4.17.21:
    resolution: {integrity: sha512-lodash==}
    dev: false
`;

      const result = parseLockfile('pnpm-lock.yaml', content);
      expect(result.has('lodash')).toBe(true);
      expect(result.get('lodash')?.version).toBe('4.17.21');
      expect(result.get('lodash')?.dev).toBe(false);
      expect(result.get('lodash')?.integrity).toBe('sha512-lodash==');
      expect(result.has('typescript')).toBe(true);
      expect(result.get('typescript')?.version).toBe('5.0.0');
      expect(result.get('typescript')?.dev).toBe(true);
    });

    it('parses pnpm lockfileVersion 9 importers, peer suffixes and package integrity', () => {
      const content = `---
lockfileVersion: '9.0'

importers:

  .:
    devDependencies:
      tsup:
        specifier: ^8.5.1
        version: 8.5.1(postcss@8.5.28)(tsx@4.23.13)
    dependencies:
      '@scope/pkg':
        specifier: ^2.1.0
        version: 2.1.3

  packages/app:
    dependencies:
      left-pad:
        specifier: ^1.3.0
        version: 1.3.0

packages:

  tsup@8.5.1:
    resolution: {integrity: sha512-tsup==}

  '@scope/pkg@2.1.3':
    resolution:
      integrity: sha512-scoped==
      tarball: https://registry.npmjs.org/@scope/pkg/-/pkg-2.1.3.tgz

  left-pad@1.3.0:
    resolution: {integrity: sha512-leftpad==}

snapshots:

  tsup@8.5.1(postcss@8.5.28)(tsx@4.23.13):
    dependencies:
      esbuild: 0.27.7
`;

      const result = parseLockfile('pnpm-lock.yaml', content);
      expect(result.get('tsup')?.version).toBe('8.5.1');
      expect(result.get('tsup')?.dev).toBe(true);
      expect(result.get('tsup')?.integrity).toBe('sha512-tsup==');
      expect(result.get('@scope/pkg')?.version).toBe('2.1.3');
      expect(result.get('@scope/pkg')?.dev).toBe(false);
      expect(result.get('@scope/pkg')?.integrity).toBe('sha512-scoped==');
      expect(result.get('@scope/pkg')?.resolved).toBe(
        'https://registry.npmjs.org/@scope/pkg/-/pkg-2.1.3.tgz'
      );
      expect(result.has('left-pad')).toBe(false);
      expect(result.has('esbuild')).toBe(false);
      expect(result.size).toBe(2);
    });

    it('ignores dependency entries declared by snapshots of other packages', () => {
      const content = `lockfileVersion: '9.0'

importers:

  .:
    dependencies:
      react-dom:
        specifier: ^18.2.0
        version: 18.2.0(react@18.2.0)

snapshots:

  react-dom@18.2.0(react@18.2.0):
    dependencies:
      react: 18.2.0
`;

      const result = parseLockfile('pnpm-lock.yaml', content);
      expect(result.get('react-dom')?.version).toBe('18.2.0');
      expect(result.has('react')).toBe(false);
    });
  });

  it('returns an empty map for unsupported lockfiles', () => {
    expect(parseLockfile('Cargo.lock', 'anything').size).toBe(0);
  });
});
